// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace KenticoCloudLocalizationDemo.Models
{
    public partial class Movie
    {
        public const string Codename = "movie";
        public const string TitleCodename = "title";
        public const string YearCodename = "year";
        public const string GenreCodename = "genre";
        public const string PosterCodename = "poster";
        public const string LinkCodename = "link";

        public string Title { get; set; }
        public decimal? Year { get; set; }
        public IEnumerable<MultipleChoiceOption> Genre { get; set; }
        public IEnumerable<Asset> Poster { get; set; }
        public string Link { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}